---
# vars file for IaC/k8s/tf/roles/k8sPrerequisites
namespaces:
  faas:
    labels:
      istio-injection: enabled
    name: "{{ faasNamespace }}"
  monitoring:
    labels:
      istio-injection: enabled
    name: "{{ monitoringNamespace }}"
  certManager:
    name: "{{ certManagerNamespace }}"
  istio:
    name: "{{ istioNamespace }}"

secrets:
  certManager:
    name: "{{ secretName }}"
    namespace: "{{ certManagerNamespace }}"
    data:
      "api-token": "{{ secretValue | b64encode }}"
  istio:
    name: "{{ secretName }}"
    namespace: "{{ istioNamespace }}"
    data:
      "api-token": "{{ secretValue | b64encode }}"
  azureDiskCsiDriver:
    name: "{{ secretNameAzureDiskCsiDriver }}"
    namespace: "{{ azureDiskCsiDriverNamespace }}"
    data:
      "cloud-config": "{{ azureJsonSecretValue | from_json | b64encode }}"
