$ANSIBLE_VAULT;1.1;AES256
61626439666264633136626265303864656537346435343539393166396138393633323734363065
3866303139376432663433353136613236623734393661320a626563363763623162373665623631
61306138303935653538333639656333623761373335333163346462323765333233633730653838
6331656633343738300a633064376333313436646563383334636439373833303334326539636138
39633939613664356234363533636466653230666134396461616532663134653138316134363832
32326461356563643534383362613935623636303738323837613630623838346264653964316132
64616231313166303638323565363063353030666136336335346435333565636335373663346235
66336165353462386663
