$ANSIBLE_VAULT;1.1;AES256
62363033373164306263383462626165316436663834366431633666323533663332333737323434
3130323334626163663635303361613935313134653931650a613961643666666536623530306637
35316530366261363933356233303965643238313966333239653231386436636336333662653731
3565326463393534360a396431396131373939346437323264303165633738633333356362323735
39643339356134346434353339653937653939636432316639656638643432303938643037656338
62306432393234663062316232336331303137646631396433663235353737633739643162626134
63383430373238626635356166656164376262623932353933303139613336636538313361366133
31306561646665653264
