$ANSIBLE_VAULT;1.1;AES256
62623836653031323666636138616635386531656434613338366162366232356431346235316466
3139353431663562333739633038376263393766333666640a383961306134613037393831306562
33333766623732633938323336373538636231653231663537666239613135626434313066373663
3836313066636235660a396331666132646163313934623734333463626638636562383564633034
34336466333261323833616665613633343431333861313436373531653239643738646134643935
33323764656638623438643465343439616435386237366335663933383336643635353230386163
34636462316231306565346536663737313862613038653166623637663939363466373035646564
62633938386335313535
