---
# tasks file for IaC/k8s/tf/roles/keepalived
- name: Configure Keepalived configuration file
  become: true
  ansible.builtin.copy:
    dest: "/etc/keepalived/keepalived.conf"
    src: "{{ keepalivedFilename }}"
  notify: restart keepalived