---
# tasks file for IaC/k8s/tf/roles/highAvailabilityProxy repos
- name: Add deb repositories
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename }}"
    update_cache: "{{ item.update_cache }}"
  loop: "{{ apt_repository.values() | flatten }}"
