---
# tasks file for IaC/k8s/tf/roles/k8sNodesPrerequisites
- name: Linux kernel configurations
  ansible.builtin.include_tasks: kernelModules.yml

- name: Add necessary repositories
  ansible.builtin.include_tasks: repos.yml

- name: Install needed packages
  ansible.builtin.include_tasks: packages.yml
