---
# tasks file for IaCaKs/tf/roles/knative manifest
- name: Apply Knative Operator Manifest File to the Cluster
  kubernetes.core.k8s:
    state: present
    src: "{{ src }}"
    host: "{{ host }}"
    ca_cert: "{{ cert.ca_cert.dest }}"
    client_key: "{{ cert.client_key.dest }}"
    client_cert: "{{ cert.client_cert.dest }}"
