---
# vars file for IaC/k8s/tf/roles/k8sAnsible
certManager:
  prod:
    name: "letsencrypt-prod"
    path: "{{ role_path }}/templates/clusterIssuer.yaml.j2"
    server: "https://acme-v02.api.letsencrypt.org/directory"
  stage:
    name: "letsencrypt-staging"
    path: "{{ role_path }}/templates/clusterIssuer.yaml.j2"
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"