---
# tasks file for IaC/k8s/tf/roles/k8s customCertKeyExtract
- name: Load custom cert key file to var
  ansible.builtin.set_fact:
    kubeClusterCertKey: "{{ lookup('file', '{{ role_path }}/files/{{ kubeadm.certCustomKeyFile }}') }}"
