---
# tasks file for IaC/k8s/tf/roles/k8s kubeadmJoinWorker
- name: Joining Worker Node
  block:
    - name: Join Worker Node
      ansible.builtin.command: |
        {{ kubeadm_token }} --cri-socket={{ kubeadm.crioUnixSocket }}
  become: true
