---
# tasks file for IaC/k8s/tf/roles/k8s kubeadmJoinSecondaryMaster
- name: Join Secondary Master Node
  ansible.builtin.shell: |
    {{ kubeadm_token }} --certificate-key {{ kubeClusterCertKey }} --cri-socket={{ kubeadm.crioUnixSocket }} --control-plane
  become: true
