---
# tasks file for IaC/k8s/tf/roles/k8s labelNode
- name: Encrypt Cert Key File
  ansible.builtin.command:
    cmd: "kubectl label node {{ ansible_hostname | lower }} kubernetes.io/role=worker"
  delegate_to: localhost
  connection: local
