---
# tasks file for IaC/k8s/tf/roles/k8s removeKubeConfig
- name: Remove kubeConfig file
  ansible.builtin.file:
    path: "{{ kubeConfigDestination | default('~/.kube/config') }}"
    state: absent
  delegate_to: localhost
  connection: local