---
# tasks file for IaC/k8s/tf/roles/k8s templateK8s
- name: Create k8s CertManager ClusterIssuer(s)
  kubernetes.core.k8s:
    state: present
    template: "{{ item.value.path }}"
    kubeconfig: "{{ kubeConfigDestination | default('~/.kube/config') }}"
  loop: "{{ lookup('ansible.builtin.dict', certManager) }}"
  connection: local
  delegate_to: localhost
